language: node_js

node_js:
  - "node"

branches:
  only:
  - master

install: npm install

cache:
  directories:
    - "node_modules"

if: tag IS present

script:
  - npm run deploy

env:
  - CLIENT_SECRET=$CLIENT_SECRET REFRESH_TOKEN=$REFRESH_TOKEN
