language: node_js

node_js:
  - "node"

branches:
  only:
  - master

install: npm install

cache:
  directories:
    - "node_modules"

script: if [[ $TRAVIS_TAG != '' ]]; then npm run deploy; fi

env:
  - CLIENT_SECRET=$CLIENT_SECRET REFRESH_TOKEN=$REFRESH_TOKEN
